language: node_js
node_js:  
  - "10"
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notifications:
  email: false
before_script:
  - npm prune
script:
after_success:
  - npm run semantic-release